export const crossWayAbi = [
  {
    type: "function",
    name: "sendToAddress",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "memo", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "sendTo",
    stateMutability: "nonpayable",
    inputs: [
      { name: "kind", type: "bytes32" },
      { name: "value", type: "string" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "expiresAt", type: "uint64" },
      { name: "memo", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "createRequest",
    stateMutability: "nonpayable",
    inputs: [
      { name: "payer", type: "address" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "expiresAt", type: "uint64" },
      { name: "memo", type: "bytes" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "createRequestTo",
    stateMutability: "nonpayable",
    inputs: [
      { name: "kind", type: "bytes32" },
      { name: "value", type: "string" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "expiresAt", type: "uint64" },
      { name: "memo", type: "bytes" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "createLink",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "expiresAt", type: "uint64" },
      { name: "memo", type: "bytes" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "pay",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "memo", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "invoices",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [
      { name: "payee", type: "address" },
      { name: "payer", type: "address" },
      { name: "payerKey", type: "bytes32" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "expiresAt", type: "uint64" },
      { name: "kind", type: "uint8" },
      { name: "closed", type: "bool" },
    ],
  },
  {
    type: "event",
    name: "Paid",
    inputs: [
      { name: "from", type: "address", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "token", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "key", type: "bytes32", indexed: false },
      { name: "method", type: "uint8", indexed: false },
      { name: "refId", type: "uint256", indexed: false },
      { name: "memo", type: "bytes", indexed: false },
    ],
  },
] as const;
